# This is a basic workflow to help you get started with Actions

name: CreateBranch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
    branches: [
      feature/*,
      bugfix/*,
      hotfix/*
    ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git config --global user.email "kushalbhatia169@gmail.com"
          git config --global user.name "kushalbhatia169"
          sed -i 's/https:\/\/baatcheet-77.herokuapp.com/http:\/\/localhost:8000/g' client/src/config.json
          sed -i 's/wss:\/\/baatcheet-77.herokuapp.com/ws:\/\/127.0.0.1:8000/g' client/src/config.json
          cat client/src/config.json
          git add .
          git commit -a --allow-empty-message -m "[skip CI]"
          git push